<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        <ApplicationIcon>Assets\Icons\icon.ico</ApplicationIcon>
        <BuildDate>$([System.DateTime]::Now.ToString('dd.MM.yyyy'))</BuildDate>
    </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<SelfContained>true</SelfContained>
		<PublishSingleFile>true</PublishSingleFile>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
	</PropertyGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
            <_Parameter1>BuildDate</_Parameter1>
            <_Parameter2>$(BuildDate)</_Parameter2>
        </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
      <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
      <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.9" />
      <PackageReference Include="Serilog" Version="4.3.1" />
      <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
      <PackageReference Include="Serilog.Sinks.File" Version="7.0.1-dev-02315" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Recon.Core\Recon.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Assets\" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Assets\Icons\icon.ico" />
      <Resource Include="Assets\Icons\icon.ico" />
    </ItemGroup>

    <ItemGroup>
      <Page Update="Dialogs\InputWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>

</Project>
